author: Xzonn
image_cdn: https://images.xzonn.top/github
cdnpath: https://cdn.jsdelivr.net/gh/Xzonn/xzonn.github.io@v4.0
defaults:
  - values:
      base_css: "base"
      layout: "default"
name: 3DS游戏《路易吉洋馆》专题站
plugins:
  - jekyll-sitemap